{{- if .Values.postman.collection.inline }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "newman-api-tester.fullname" . }}-collection
  labels:
    {{- include "newman-api-tester.labels" . | nindent 4 }}
data:
  {{ .Values.postman.collection.filename }}: |
    {{- .Values.postman.collection.inline | nindent 4 }}
{{- end }}
{{- if .Values.postman.environment.inline }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "newman-api-tester.fullname" . }}-environment
  labels:
    {{- include "newman-api-tester.labels" . | nindent 4 }}
data:
  {{ .Values.postman.environment.filename }}: |
    {{- .Values.postman.environment.inline | nindent 4 }}
{{- end }}
