{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "newman-api-tester.fullname" . }}
  labels:
    {{- include "newman-api-tester.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  {{- if .Values.cronjob.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ .Values.cronjob.startingDeadlineSeconds }}
  {{- end }}
  jobTemplate:
    metadata:
      labels:
        {{- include "newman-api-tester.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.cronjob.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ .Values.cronjob.activeDeadlineSeconds }}
      {{- end }}
      {{- if .Values.cronjob.ttlSecondsAfterFinished }}
      ttlSecondsAfterFinished: {{ .Values.cronjob.ttlSecondsAfterFinished }}
      {{- end }}
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "newman-api-tester.selectorLabels" . | nindent 12 }}
            {{- with .Values.podLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          annotations:
            {{- with .Values.podAnnotations }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "newman-api-tester.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          {{- with .Values.initContainers }}
          initContainers:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              # Using args instead of command to leverage newman entrypoint
              args:
                - run
                {{- if .Values.postman.collection.configMap }}
                - /newman/collections/{{ .Values.postman.collection.filename }}
                {{- else if .Values.postman.collection.inline }}
                - /newman/collections/{{ .Values.postman.collection.filename }}
                {{- else if .Values.postman.collection.url }}
                - {{ .Values.postman.collection.url }}
                {{- else }}
                - collection.json
                {{- end }}
                {{- if .Values.postman.environment.configMap }}
                - -e
                - /newman/environments/{{ .Values.postman.environment.filename }}
                {{- else if .Values.postman.environment.inline }}
                - -e
                - /newman/environments/{{ .Values.postman.environment.filename }}
                {{- else if .Values.postman.environment.url }}
                - -e
                - {{ .Values.postman.environment.url }}
                {{- end }}
                {{- range $key, $value := .Values.newman.options }}
                - --{{ $key }}
                - {{ $value | quote }}
                {{- end }}
                {{- if .Values.newman.reporters }}
                - --reporters
                - {{ join "," .Values.newman.reporters }}
                {{- end }}
                {{- if .Values.newman.customArgs }}
                # Custom args passed as a single string, needs to be split
                {{- range (split " " .Values.newman.customArgs) }}
                - {{ . }}
                {{- end }}
                {{- end }}
              {{- with .Values.env }}
              env:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              volumeMounts:
                {{- if or .Values.postman.collection.configMap .Values.postman.collection.inline }}
                - name: collection
                  mountPath: /newman/collections
                  readOnly: true
                {{- end }}
                {{- if or .Values.postman.environment.configMap .Values.postman.environment.inline }}
                - name: environment
                  mountPath: /newman/environments
                  readOnly: true
                {{- end }}
                {{- with .Values.volumeMounts }}
                {{- toYaml . | nindent 16 }}
                {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          volumes:
            {{- if .Values.postman.collection.configMap }}
            - name: collection
              configMap:
                name: {{ .Values.postman.collection.configMap }}
            {{- else if .Values.postman.collection.inline }}
            - name: collection
              configMap:
                name: {{ include "newman-api-tester.fullname" . }}-collection
            {{- end }}
            {{- if .Values.postman.environment.configMap }}
            - name: environment
              configMap:
                name: {{ .Values.postman.environment.configMap }}
            {{- else if .Values.postman.environment.inline }}
            - name: environment
              configMap:
                name: {{ include "newman-api-tester.fullname" . }}-environment
            {{- end }}
            {{- with .Values.volumes }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}