name: Publish Helm Chart

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  release-helm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to GitHub Container Registry  
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and push Helm chart
        run: |
          helm package .
          helm push *.tgz oci://ghcr.io/doublewordai
